package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.TbUserVip;
import org.linlinjava.litemall.db.domain.TbUserVipExample;

public interface TbUserVipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_vip
     *
     * @mbg.generated
     */
    long countByExample(TbUserVipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_vip
     *
     * @mbg.generated
     */
    int deleteByExample(TbUserVipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_vip
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_vip
     *
     * @mbg.generated
     */
    int insert(TbUserVip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_vip
     *
     * @mbg.generated
     */
    int insertSelective(TbUserVip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_vip
     *
     * @mbg.generated
     */
    TbUserVip selectOneByExample(TbUserVipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_vip
     *
     * @mbg.generated
     */
    TbUserVip selectOneByExampleSelective(@Param("example") TbUserVipExample example, @Param("selective") TbUserVip.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_vip
     *
     * @mbg.generated
     */
    List<TbUserVip> selectByExampleSelective(@Param("example") TbUserVipExample example, @Param("selective") TbUserVip.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_vip
     *
     * @mbg.generated
     */
    List<TbUserVip> selectByExample(TbUserVipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_vip
     *
     * @mbg.generated
     */
    TbUserVip selectByPrimaryKeySelective(@Param("id") Long id, @Param("selective") TbUserVip.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_vip
     *
     * @mbg.generated
     */
    TbUserVip selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_vip
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbUserVip record, @Param("example") TbUserVipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_vip
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbUserVip record, @Param("example") TbUserVipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_vip
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbUserVip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_vip
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbUserVip record);

    TbUserVip selectByUserId(@Param("userId") Integer userId);
}